# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemap < Formula
  desc "a tool that helps annotate code files with structural information to provide better context for LLMs (Large Language Models)."
  homepage "https://github.com/krzko/codemap"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/krzko/codemap/releases/download/v0.1.0/codemap_darwin_amd64.tar.gz"
      sha256 "e15d5c00a6bfe12565f07d18216cdbde651465d97b478ba594233a8fcd2bfa73"

      def install
        bin.install "codemap"
      end
    end
    on_arm do
      url "https://github.com/krzko/codemap/releases/download/v0.1.0/codemap_darwin_arm64.tar.gz"
      sha256 "b35bbd5c4fcc19840899006f9547091ddaf20a91174949ae0db8368a89d14041"

      def install
        bin.install "codemap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/codemap/releases/download/v0.1.0/codemap_linux_amd64.tar.gz"
        sha256 "c8829c5c6538de167760acb2f8b11c2385be52801a2e22c919f6c0cb12c87007"

        def install
          bin.install "codemap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/codemap/releases/download/v0.1.0/codemap_linux_arm64.tar.gz"
        sha256 "b9c0c9281ff67e2113756cb754f43206faced8ff2a7c83afc5ef616d197e546c"

        def install
          bin.install "codemap"
        end
      end
    end
  end

  test do
    system "#{bin}/codemap -v"
  end
end
