# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codemap < Formula
  desc "a tool that helps annotate code files with structural information to provide better context for LLMs (Large Language Models)."
  homepage "https://github.com/krzko/codemap"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/krzko/codemap/releases/download/v0.2.0/codemap_darwin_amd64.tar.gz"
      sha256 "baf1c40ff76b325bc78c1a919614b70ad6ce4128e2addca184ba451dfaa623cc"

      def install
        bin.install "codemap"
      end
    end
    on_arm do
      url "https://github.com/krzko/codemap/releases/download/v0.2.0/codemap_darwin_arm64.tar.gz"
      sha256 "cc43348f791c7565c9fe575efebf9b391278be5da2799e01e5b6ae648363ed3d"

      def install
        bin.install "codemap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/codemap/releases/download/v0.2.0/codemap_linux_amd64.tar.gz"
        sha256 "dd5e300abc4263d1788299ff73b1440af8244996463d6dadd5f6e26c91384e78"

        def install
          bin.install "codemap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/codemap/releases/download/v0.2.0/codemap_linux_arm64.tar.gz"
        sha256 "0fd1137499ea51f4a7dacaaf2e2faed992cfa138d76581e1f561e6455c5e8412"

        def install
          bin.install "codemap"
        end
      end
    end
  end

  test do
    system "#{bin}/codemap -v"
  end
end
