# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jiragitfluence < Formula
  desc "A tool to aggregate data from Jira and GitHub and publish it to Confluence."
  homepage "https://github.com/krzko/jiragitfluence"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krzko/jiragitfluence/releases/download/v0.1.0/jiragitfluence_darwin_amd64.tar.gz"
      sha256 "134b49927c16050db39daf91812bd766f5f0aa8871730cd9273986f0b406b376"

      def install
        bin.install "jiragitfluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krzko/jiragitfluence/releases/download/v0.1.0/jiragitfluence_darwin_arm64.tar.gz"
      sha256 "4ca1d220f8feb99ad15f45135ce7fe1c2ccb42226a006f95fe600da9387e2d34"

      def install
        bin.install "jiragitfluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/jiragitfluence/releases/download/v0.1.0/jiragitfluence_linux_amd64.tar.gz"
        sha256 "c9917d4c872740ea6efd119adbe7682b26c6307f7df9cebe2ae562c20f4eb9d7"

        def install
          bin.install "jiragitfluence"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/jiragitfluence/releases/download/v0.1.0/jiragitfluence_linux_arm64.tar.gz"
        sha256 "55af394bcc699782ce3faadf01d7d8effb77f9cb7fd434be7c260f60589f8bbc"

        def install
          bin.install "jiragitfluence"
        end
      end
    end
  end

  test do
    system "#{bin}/jiragitfluence -v"
  end
end
