# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpentelemetryShell < Formula
  desc "OpenTelemetry functions for shells"
  homepage "https://github.com/krzko/opentelemetry-shell"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.6/opentelemetry-shell_0.0.6_darwin_arm64.tar.gz"
      sha256 "0bb82c3522bc9f640f7b54b28bbd5abc15e3900c9db8cb598338698ac44f3081"

      def install
        system "make install"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.6/opentelemetry-shell_0.0.6_darwin_amd64.tar.gz"
      sha256 "691fb3055421178a456faf0fe794814fe4dfdd8ea5ec5acf261633f088789bde"

      def install
        system "make install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.6/opentelemetry-shell_0.0.6_linux_arm64.tar.gz"
      sha256 "0d80f05d5bc1b97dabb93a579de6742d1423ee50e2f7b4275bc759ed095ad5ed"

      def install
        system "make install"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.6/opentelemetry-shell_0.0.6_linux_amd64.tar.gz"
      sha256 "7d0e822c6f1dad51ca643e8984712663d9838d7e40fb831cd37d6b97e257b1f0"

      def install
        system "make install"
      end
    end
  end

  depends_on "curl"
  depends_on "jq"

  test do
    system "make version"
  end
end
