# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpentelemetryShell < Formula
  desc "OpenTelemetry functions for shells"
  homepage "https://github.com/krzko/opentelemetry-shell"
  version "0.0.9"

  depends_on "curl"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.9/opentelemetry-shell_0.0.9_darwin_arm64.tar.gz"
      sha256 "b3721201893adec2eb18446a2ac913ad1af24dbc8b7199772b0a401718e80a6a"

      def install
        system "make", "install"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.9/opentelemetry-shell_0.0.9_darwin_amd64.tar.gz"
      sha256 "acb31357743a9baf6ee8469fd6b8fa4b44c68466614a406e3942291bafc6d3fd"

      def install
        system "make", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.9/opentelemetry-shell_0.0.9_linux_arm64.tar.gz"
      sha256 "52503bbb85248bb5a1bb8723cce497de2751d148e1911b475e252b1b929abcd8"

      def install
        system "make", "install"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.9/opentelemetry-shell_0.0.9_linux_amd64.tar.gz"
      sha256 "cf6416a78356ad7710aadec95414c947d231816dd623ce5488dab1d3720eccdf"

      def install
        system "make", "install"
      end
    end
  end

  test do
    system "make", "version"
  end
end
