# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpentelemetryShell < Formula
  desc "OpenTelemetry functions for shells"
  homepage "https://github.com/krzko/opentelemetry-shell"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.2/opentelemetry-shell_0.0.2_darwin_arm64.tar.gz"
      sha256 "c29ee51a7f4208d759a42ebeb86aa56ef7f08c9f010407b5b3c1da24276763a5"

      def install
        system "make" "install"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.2/opentelemetry-shell_0.0.2_darwin_amd64.tar.gz"
      sha256 "6171507448725a1f7d964cb2ec609cde5d8fbd3e88b1693529e7c041475e75c4"

      def install
        system "make" "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.2/opentelemetry-shell_0.0.2_linux_amd64.tar.gz"
      sha256 "bf177f2b8b08c3d6c9ac5a68be5a4b6bebe597fe218c1b26bf7b9a97a4632cc4"

      def install
        system "make" "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/opentelemetry-shell/releases/download/v0.0.2/opentelemetry-shell_0.0.2_linux_arm64.tar.gz"
      sha256 "8b2e72c7358e5a5af25cbf3cdb07dad6530804cc5915f842333211bc3fe19233"

      def install
        system "make" "install"
      end
    end
  end

  test do
    system "make" "version"
  end
end
