# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oteldemo < Formula
  desc "OpenTelemetry Demo Generator."
  homepage "https://github.com/krzko/oteldemo"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.1/oteldemo_darwin_amd64.tar.gz"
      sha256 "738f38450fdeda84d272ea7c122b4c6f1c3604988bf9064dc419ca97f19df7b7"

      def install
        bin.install "oteldemo"
      end
    end
    on_arm do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.1/oteldemo_darwin_arm64.tar.gz"
      sha256 "0974c0c275ded8a3847eea3cfa060cea689b71ebcbc731552832cd2546a1ea7f"

      def install
        bin.install "oteldemo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.1/oteldemo_linux_amd64.tar.gz"
        sha256 "fe0ea85697771a869b10a2ade5c5a3902ea6dad9024658ccdb47c04668c9a9db"

        def install
          bin.install "oteldemo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.1/oteldemo_linux_arm64.tar.gz"
        sha256 "7dfe93a0114a488c0219e40e942f12d91a90e0d8aaf6435465774e3002699aae"

        def install
          bin.install "oteldemo"
        end
      end
    end
  end

  test do
    system "#{bin}/oteldemo -v"
  end
end
