# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oteldemo < Formula
  desc "OpenTelemetry Demo Generator."
  homepage "https://github.com/krzko/oteldemo"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.0/oteldemo_darwin_amd64.tar.gz"
      sha256 "381a4c8c3b7624d51cefe543266bc0b648857eab930ce96bcc8130cf17f2000c"

      def install
        bin.install "oteldemo"
      end
    end
    on_arm do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.0/oteldemo_darwin_arm64.tar.gz"
      sha256 "120e8498ec6188e71a424f0b1b035099982c37bcf5dbb9e3e3e40e185c697b4e"

      def install
        bin.install "oteldemo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.0/oteldemo_linux_amd64.tar.gz"
        sha256 "a704b752fb416f3b595d33389b57c2ef8fa66f09502ee860f7a0b845f6f09e98"

        def install
          bin.install "oteldemo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.0/oteldemo_linux_arm64.tar.gz"
        sha256 "a972043d2d5929c50214bfb7402ae9c9138d58adbcfb20ad45d033db979eb186"

        def install
          bin.install "oteldemo"
        end
      end
    end
  end

  test do
    system "#{bin}/oteldemo -v"
  end
end
