# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelgen < Formula
  desc "A tool to generate synthetic OpenTelemetry logs, metrics and traces telemetry data."
  homepage "https://github.com/krzko/otelgen"
  version "0.5.2"

  on_macos do
    on_intel do
      url "https://github.com/krzko/otelgen/releases/download/v0.5.2/otelgen_darwin_amd64.tar.gz"
      sha256 "c3ee5ea3cea3b2b97a8924901bb28fc9972448aed9eaad6230fe93425a8b879e"

      def install
        bin.install "otelgen"
      end
    end
    on_arm do
      url "https://github.com/krzko/otelgen/releases/download/v0.5.2/otelgen_darwin_arm64.tar.gz"
      sha256 "5a31182855be5ed374466eb5f42ed8fd85edf462ce54bc6c50e41de294321059"

      def install
        bin.install "otelgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/otelgen/releases/download/v0.5.2/otelgen_linux_amd64.tar.gz"
        sha256 "96e1b9d2d297691d01a5c377758a83428918b404075687fa83df2e300f5c1555"

        def install
          bin.install "otelgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/otelgen/releases/download/v0.5.2/otelgen_linux_arm64.tar.gz"
        sha256 "0579ce5f78e75ef172164b6cab37342068b313ff1359442c87221205c72586df"

        def install
          bin.install "otelgen"
        end
      end
    end
  end

  test do
    system "#{bin}/otelgen -v"
  end
end
