# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelgen < Formula
  desc "A tool to generate synthetic OpenTelemetry logs, metrics and traces, the core observability pillars"
  homepage "https://github.com/krzko/otelgen"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/otelgen/releases/download/v0.4.0/otelgen_darwin_arm64.tar.gz"
      sha256 "4a1b702c59795e81d1d94abed85349edf1637bb07e69949b727b8d881c17bad9"

      def install
        bin.install "otelgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/otelgen/releases/download/v0.4.0/otelgen_darwin_amd64.tar.gz"
      sha256 "de8100bba5fcc10ba1aa0e6547307948a47161b9f20c44e4ac877a6f1dc28a1b"

      def install
        bin.install "otelgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/otelgen/releases/download/v0.4.0/otelgen_linux_arm64.tar.gz"
      sha256 "90cc74e9a90a087b65901177bbc18e94437c87bdf528c4cf45b572c12a7f2cda"

      def install
        bin.install "otelgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/otelgen/releases/download/v0.4.0/otelgen_linux_amd64.tar.gz"
      sha256 "d79a1abda27776432df45e0384111adbdd4980253d0c50d19ed81f9672a4dd5b"

      def install
        bin.install "otelgen"
      end
    end
  end

  test do
    system "#{bin}/otelgen -v"
  end
end
