# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oteldemo < Formula
  desc "OpenTelemetry Demo Generator."
  homepage "https://github.com/krzko/oteldemo"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.2/oteldemo_darwin_amd64.tar.gz"
      sha256 "ffd5cbca7c6741178b7ac344fb2c937c03c17bf09aa351f19082465552109275"

      def install
        bin.install "oteldemo"
      end
    end
    on_arm do
      url "https://github.com/krzko/oteldemo/releases/download/v0.1.2/oteldemo_darwin_arm64.tar.gz"
      sha256 "2054c70ea5fa5d936be35f06bfbcb876e9151229afe1566f5ea254bccced7c0d"

      def install
        bin.install "oteldemo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.2/oteldemo_linux_amd64.tar.gz"
        sha256 "d95c702d5798d62664044564cbd1351cd494fa950e6872f3153fee3f0cd5cdec"

        def install
          bin.install "oteldemo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/oteldemo/releases/download/v0.1.2/oteldemo_linux_arm64.tar.gz"
        sha256 "f544ffefe3c39362909398f69668dc15bf155a45946206baf87b427f53ce6183"

        def install
          bin.install "oteldemo"
        end
      end
    end
  end

  test do
    system "#{bin}/oteldemo -v"
  end
end
