# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otelgen < Formula
  desc "A tool to generate synthetic OpenTelemetry logs, metrics and traces, the core observability pillars"
  homepage "https://github.com/krzko/otelgen"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/otelgen/releases/download/v0.3.2/otelgen_darwin_arm64.tar.gz"
      sha256 "32079df5c7dc00c2d15d1a6e9797de2efaba669226eaa56b155184d46b75e8c2"

      def install
        bin.install "otelgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/otelgen/releases/download/v0.3.2/otelgen_darwin_amd64.tar.gz"
      sha256 "2920bf398ddd12ae883925caf1db66dfcb07f31bd27ac849b180f5ade6121f04"

      def install
        bin.install "otelgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/otelgen/releases/download/v0.3.2/otelgen_linux_arm64.tar.gz"
      sha256 "de71381d6208edbcf4803dedd0e97cf8f4d865182694030f40b3dff412a08ad4"

      def install
        bin.install "otelgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/otelgen/releases/download/v0.3.2/otelgen_linux_amd64.tar.gz"
      sha256 "d52baf7fae8f7818253e121c65d249128ab8a80dcab744af14265e89e1c1f2c8"

      def install
        bin.install "otelgen"
      end
    end
  end

  test do
    system "#{bin}/otelgen -v"
  end
end
