# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto2yaml < Formula
  desc "A command-line utility to export Protocol Buffers (proto) files to YAML, and JSON"
  homepage "https://github.com/krzko/proto2yaml"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.0.6/proto2yaml_darwin_amd64.tar.gz"
      sha256 "4fd0c42f4728f7db3983d276a6db1690aabb92f45e64ed3611677936f42921e2"

      def install
        bin.install "proto2yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.0.6/proto2yaml_darwin_arm64.tar.gz"
      sha256 "3dfa7b66fa9e3148a49d818d230e046774564a2993af8eb785c453cf8fd79521"

      def install
        bin.install "proto2yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.0.6/proto2yaml_linux_arm64.tar.gz"
      sha256 "2a167020e9ecacb654da88440dece97408c56fb17a6ef3b31d78f68b5a3eb63e"

      def install
        bin.install "proto2yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.0.6/proto2yaml_linux_amd64.tar.gz"
      sha256 "a8d24c2d36fdb6232c76374975add5ab126b2575444f0a9e453cb4905473aad6"

      def install
        bin.install "proto2yaml"
      end
    end
  end

  test do
    system "#{bin}/proto2yaml -v"
  end
end
