# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proto2yaml < Formula
  desc "A command-line utility to export Protocol Buffers (proto) files to YAML, and JSON"
  homepage "https://github.com/krzko/proto2yaml"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.6.0/proto2yaml_darwin_arm64.tar.gz"
      sha256 "4fb8f2278e538b4e4eae1c5afd1ca24bd612f1afab20ed1c657eaaa36f54750b"

      def install
        bin.install "proto2yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.6.0/proto2yaml_darwin_amd64.tar.gz"
      sha256 "cdc30ae532f7093725845836fc8d76eed0618d6783095cf3f35c52b7f580d80b"

      def install
        bin.install "proto2yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.6.0/proto2yaml_linux_arm64.tar.gz"
      sha256 "1517a8b4533f7219ccc207ee13593040eabe4b73fb7c3b7af8751e7a9134dea1"

      def install
        bin.install "proto2yaml"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/proto2yaml/releases/download/v0.6.0/proto2yaml_linux_amd64.tar.gz"
      sha256 "e27d862404526bfe29d35c6bc4d223fa3f876fc624dfbfb52275bfd7b1f77997"

      def install
        bin.install "proto2yaml"
      end
    end
  end

  test do
    system "#{bin}/proto2yaml -v"
  end
end
