# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restmigrate < Formula
  desc "Restmigrate is a tool for managing REST API configuration migrations, inspired by database schema migration tools"
  homepage "https://github.com/krzko/restmigrate"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/krzko/restmigrate/releases/download/v0.1.3/restmigrate_darwin_amd64.tar.gz"
      sha256 "1a2e6856ff3d498435cccbbd52f476c2e24a4b51b6ffb55477fcabf0e8b84438"

      def install
        bin.install "restmigrate"
      end
    end
    on_arm do
      url "https://github.com/krzko/restmigrate/releases/download/v0.1.3/restmigrate_darwin_arm64.tar.gz"
      sha256 "c17f79f27fa5494c1f1bc979bfa86e6f18e19d20fc561783254bc6286f15381c"

      def install
        bin.install "restmigrate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/restmigrate/releases/download/v0.1.3/restmigrate_linux_amd64.tar.gz"
        sha256 "6bf852ca7e7692c9a9a27c69ce07b21ef1b382787ce4eca99cef13bbad67a295"

        def install
          bin.install "restmigrate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/krzko/restmigrate/releases/download/v0.1.3/restmigrate_linux_arm64.tar.gz"
        sha256 "18a1adde80f04e33162a1ed895595c808e8fef0b19b6a395d0ea91b641f9d974"

        def install
          bin.install "restmigrate"
        end
      end
    end
  end

  test do
    system "#{bin}/restmigrate -v"
  end
end
