# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RunO11yRun < Formula
  desc "A single-binary 🌯 wrapper around `docker compose` with embedded configurations to effortlessly run your local observability stack"
  homepage "https://github.com/krzko/run-o11y-run"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krzko/run-o11y-run/releases/download/v0.4.0/run-o11y-run_darwin_amd64.tar.gz"
      sha256 "1baf5cf728b2263a0edc1b4be2204ba5b62a96841fcbdf7ca86ac24fceef8be5"

      def install
        bin.install "run-o11y-run"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krzko/run-o11y-run/releases/download/v0.4.0/run-o11y-run_darwin_arm64.tar.gz"
      sha256 "db0e65fbdcbaeb6ea9b02c0c6e3d401ac60bc0db7d35154033fa8e79f868aa15"

      def install
        bin.install "run-o11y-run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krzko/run-o11y-run/releases/download/v0.4.0/run-o11y-run_linux_amd64.tar.gz"
      sha256 "4878aabbe2d67e4e15ae9b1cba97f584f2b913a6fdaa5db584f7d0831802e252"

      def install
        bin.install "run-o11y-run"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/run-o11y-run/releases/download/v0.4.0/run-o11y-run_linux_arm64.tar.gz"
      sha256 "895cb5f4cdbb4d72686ae4d8f8624acea5e52870cba41254ba1c29935007d3bb"

      def install
        bin.install "run-o11y-run"
      end
    end
  end

  test do
    system "#{bin}/run-o11y-run -v"
  end
end
