# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvctl < Formula
  desc "A command-line utility to interact with TradingView"
  homepage "https://github.com/krzko/tvctl"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.5/tvctl_Darwin_arm64.tar.gz"
      sha256 "35f7e55b4f93a57af892da73dca6d5e4d49f18708e6a7537f431770cc07fa264"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.5/tvctl_Darwin_x86_64.tar.gz"
      sha256 "daa68f131980b7147598cdc62796f2ca1623ca463e6bbba720e30fa84be49e86"

      def install
        bin.install "tvctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.5/tvctl_Linux_arm64.tar.gz"
      sha256 "7775ecf356d8851185a040bd5ef5b168464501110ccda6dc3387bc0b6f4058ad"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.5/tvctl_Linux_x86_64.tar.gz"
      sha256 "b5fe5e99514dac5dd78293688c6ed0e2ae4b38aee87cc7fbafa6fe49b1e44cf9"

      def install
        bin.install "tvctl"
      end
    end
  end

  depends_on "go"

  test do
    system "#{bin}/tvctl -v"
  end
end
