# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvctl < Formula
  desc "A command-line utility to interact with TradingView"
  homepage "https://github.com/krzko/tvctl"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/tvctl/releases/download/v0.7.1/tvctl_darwin_arm64.tar.gz"
      sha256 "9a91083faf385810524f53d7dfac7b4d85b19def23b09b14fd73193fe4323010"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.7.1/tvctl_darwin_amd64.tar.gz"
      sha256 "583bc5b5c6dc840734b17da1cb8c38e8820a1f436b7c168700c83e30444e62ff"

      def install
        bin.install "tvctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/tvctl/releases/download/v0.7.1/tvctl_linux_arm64.tar.gz"
      sha256 "16eb035ef1c6fe0bcbfa5cbd2cbcc5db5bbdda2f396c6c2ccd19fd22a4dc54e6"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.7.1/tvctl_linux_amd64.tar.gz"
      sha256 "7b4c505c807f2c4db948b6298b5444258b48712bc0d485cacab50c38d41ac787"

      def install
        bin.install "tvctl"
      end
    end
  end

  test do
    system "#{bin}/tvctl -v"
  end
end
