# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvctl < Formula
  desc "A command-line utility to interact with TradingView"
  homepage "https://github.com/krzko/tvctl"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.7/tvctl_darwin_arm64.tar.gz"
      sha256 "3fe203ae4d5fda8a60bb66e2f2d086ffdd72a128a1b83b0caa2054caed0db4e3"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.7/tvctl_darwin_amd64.tar.gz"
      sha256 "c791fe987b33b6bb4028575963227fdf807597b8bd53775a116b0375d8691407"

      def install
        bin.install "tvctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.7/tvctl_linux_arm64.tar.gz"
      sha256 "05678b779a2c4c35ed8223b1b3ffe9cee3fa1173017bd9e11bcf16e83504d8dd"

      def install
        bin.install "tvctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/krzko/tvctl/releases/download/v0.0.7/tvctl_linux_amd64.tar.gz"
      sha256 "bc4898d2b547211aa343330ae8a318e08fcd66ef3127e0bba353e284f8f7612a"

      def install
        bin.install "tvctl"
      end
    end
  end

  test do
    system "#{bin}/tvctl -v"
  end
end
